/*@ gen-okeys.h, generated by make-okey-map.pl.
 *@ See accmacvar.c for more */

static char const a_amv_var_names[] = {
   /* 0. [0]+15 --special-param, a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS */
   '-','-','s','p','e','c','i','a','l','-','p','a','r','a','m','\0',
   /* 1. [16]+1 ?, a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS */
   '?','\0',
   /* 2. [18]+1 !, a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS */
   '!','\0',
   /* 3. [20]+7 account, a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS */
   'a','c','c','o','u','n','t','\0',
   /* 4. [28]+19 add-file-recipients, a_AMV_VF_BOOL */
   'a','d','d','-','f','i','l','e','-','r','e','c','i','p','i','e','n','t','s','\0',
   /* 5. [48]+18 agent-shell-lookup, a_AMV_VF_OBSOLETE */
   'a','g','e','n','t','-','s','h','e','l','l','-','l','o','o','k','u','p','\0',
   /* 6. [67]+6 allnet, a_AMV_VF_BOOL */
   'a','l','l','n','e','t','\0',
   /* 7. [74]+6 append, a_AMV_VF_BOOL */
   'a','p','p','e','n','d','\0',
   /* 8. [81]+3 ask, a_AMV_VF_BOOL|a_AMV_VF_VIP */
   'a','s','k','\0',
   /* 9. [85]+8 askatend, a_AMV_VF_BOOL */
   'a','s','k','a','t','e','n','d','\0',
   /* 10. [94]+9 askattach, a_AMV_VF_BOOL */
   'a','s','k','a','t','t','a','c','h','\0',
   /* 11. [104]+6 askbcc, a_AMV_VF_BOOL */
   'a','s','k','b','c','c','\0',
   /* 12. [111]+5 askcc, a_AMV_VF_BOOL */
   'a','s','k','c','c','\0',
   /* 13. [117]+7 asksign, a_AMV_VF_BOOL */
   'a','s','k','s','i','g','n','\0',
   /* 14. [125]+7 asksend, a_AMV_VF_BOOL */
   'a','s','k','s','e','n','d','\0',
   /* 15. [133]+6 asksub, a_AMV_VF_BOOL|a_AMV_VF_I3VAL */
   'a','s','k','s','u','b','\0',
   /* 16. [140]+8 attrlist */
   'a','t','t','r','l','i','s','t','\0',
   /* 17. [149]+7 autobcc */
   'a','u','t','o','b','c','c','\0',
   /* 18. [157]+6 autocc */
   'a','u','t','o','c','c','\0',
   /* 19. [164]+12 autocollapse, a_AMV_VF_BOOL */
   'a','u','t','o','c','o','l','l','a','p','s','e','\0',
   /* 20. [177]+9 autoprint, a_AMV_VF_BOOL */
   'a','u','t','o','p','r','i','n','t','\0',
   /* 21. [187]+10 autothread, a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE */
   'a','u','t','o','t','h','r','e','a','d','\0',
   /* 22. [198]+8 autosort */
   'a','u','t','o','s','o','r','t','\0',
   /* 23. [207]+4 bang, a_AMV_VF_BOOL */
   'b','a','n','g','\0',
   /* 24. [212]+12 bind-timeout, a_AMV_VF_VIP|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM|a_AMV_VF_OBSOLETE */
   'b','i','n','d','-','t','i','m','e','o','u','t','\0',
   /* 25. [225]+23 bind-inter-byte-timeout, a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   'b','i','n','d','-','i','n','t','e','r','-','b','y','t','e','-','t','i','m','e','o','u','t','\0',
   /* 26. [249]+22 bind-inter-key-timeout, a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   'b','i','n','d','-','i','n','t','e','r','-','k','e','y','-','t','i','m','e','o','u','t','\0',
   /* 27. [272]+11 bsdannounce, a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE */
   'b','s','d','a','n','n','o','u','n','c','e','\0',
   /* 28. [284]+9 bsdcompat, a_AMV_VF_BOOL */
   'b','s','d','c','o','m','p','a','t','\0',
   /* 29. [294]+8 bsdflags, a_AMV_VF_BOOL */
   'b','s','d','f','l','a','g','s','\0',
   /* 30. [303]+11 bsdheadline, a_AMV_VF_BOOL */
   'b','s','d','h','e','a','d','l','i','n','e','\0',
   /* 31. [315]+7 bsdmsgs, a_AMV_VF_BOOL */
   'b','s','d','m','s','g','s','\0',
   /* 32. [323]+8 bsdorder, a_AMV_VF_BOOL */
   'b','s','d','o','r','d','e','r','\0',
   /* 33. [332]+8 build-cc, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'b','u','i','l','d','-','c','c','\0',
   /* 34. [341]+8 build-ld, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'b','u','i','l','d','-','l','d','\0',
   /* 35. [350]+8 build-os, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'b','u','i','l','d','-','o','s','\0',
   /* 36. [359]+10 build-rest, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'b','u','i','l','d','-','r','e','s','t','\0',
   /* 37. [370]+7 COLUMNS, a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   'C','O','L','U','M','N','S','\0',
   /* 38. [378]+12 charset-7bit, a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY */
   'c','h','a','r','s','e','t','-','7','b','i','t','\0',
   /* 39. [391]+12 charset-8bit, a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY */
   'c','h','a','r','s','e','t','-','8','b','i','t','\0',
   /* 40. [404]+20 charset-unknown-8bit, a_AMV_VF_VIP */
   'c','h','a','r','s','e','t','-','u','n','k','n','o','w','n','-','8','b','i','t','\0',
   /* 41. [425]+3 cmd */
   'c','m','d','\0',
   /* 42. [429]+14 colour-disable, a_AMV_VF_BOOL */
   'c','o','l','o','u','r','-','d','i','s','a','b','l','e','\0',
   /* 43. [444]+12 colour-pager, a_AMV_VF_BOOL */
   'c','o','l','o','u','r','-','p','a','g','e','r','\0',
   /* 44. [457]+12 contact-mail, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'c','o','n','t','a','c','t','-','m','a','i','l','\0',
   /* 45. [470]+11 contact-web, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'c','o','n','t','a','c','t','-','w','e','b','\0',
   /* 46. [482]+37 content-description-forwarded-message, a_AMV_VF_DEFVAL */
   'c','o','n','t','e','n','t','-','d','e','s','c','r','i','p','t','i','o','n','-','f','o','r','w','a','r','d','e','d','-','m','e','s','s','a','g','e','\0',
   /* 47. [520]+36 content-description-quote-attachment, a_AMV_VF_DEFVAL */
   'c','o','n','t','e','n','t','-','d','e','s','c','r','i','p','t','i','o','n','-','q','u','o','t','e','-','a','t','t','a','c','h','m','e','n','t','\0',
   /* 48. [557]+33 content-description-smime-message, a_AMV_VF_DEFVAL */
   'c','o','n','t','e','n','t','-','d','e','s','c','r','i','p','t','i','o','n','-','s','m','i','m','e','-','m','e','s','s','a','g','e','\0',
   /* 49. [591]+35 content-description-smime-signature, a_AMV_VF_DEFVAL */
   'c','o','n','t','e','n','t','-','d','e','s','c','r','i','p','t','i','o','n','-','s','m','i','m','e','-','s','i','g','n','a','t','u','r','e','\0',
   /* 50. [627]+3 crt, a_AMV_VF_POSNUM */
   'c','r','t','\0',
   /* 51. [631]+9 customhdr, a_AMV_VF_VIP */
   'c','u','s','t','o','m','h','d','r','\0',
   /* 52. [641]+4 DEAD, a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'D','E','A','D','\0',
   /* 53. [646]+9 datefield, a_AMV_VF_I3VAL */
   'd','a','t','e','f','i','e','l','d','\0',
   /* 54. [656]+23 datefield-markout-older, a_AMV_VF_I3VAL */
   'd','a','t','e','f','i','e','l','d','-','m','a','r','k','o','u','t','-','o','l','d','e','r','\0',
   /* 55. [680]+5 debug, a_AMV_VF_BOOL|a_AMV_VF_VIP */
   'd','e','b','u','g','\0',
   /* 56. [686]+29 disposition-notification-send, a_AMV_VF_BOOL */
   'd','i','s','p','o','s','i','t','i','o','n','-','n','o','t','i','f','i','c','a','t','i','o','n','-','s','e','n','d','\0',
   /* 57. [716]+3 dot, a_AMV_VF_BOOL */
   'd','o','t','\0',
   /* 58. [720]+15 dotlock-disable, a_AMV_VF_BOOL */
   'd','o','t','l','o','c','k','-','d','i','s','a','b','l','e','\0',
   /* 59. [736]+20 dotlock-ignore-error, a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE */
   'd','o','t','l','o','c','k','-','i','g','n','o','r','e','-','e','r','r','o','r','\0',
   /* 60. [757]+6 EDITOR, a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'E','D','I','T','O','R','\0',
   /* 61. [764]+9 editalong */
   'e','d','i','t','a','l','o','n','g','\0',
   /* 62. [774]+11 editheaders, a_AMV_VF_BOOL */
   'e','d','i','t','h','e','a','d','e','r','s','\0',
   /* 63. [786]+10 emptystart, a_AMV_VF_BOOL */
   'e','m','p','t','y','s','t','a','r','t','\0',
   /* 64. [797]+8 encoding, a_AMV_VF_OBSOLETE */
   'e','n','c','o','d','i','n','g','\0',
   /* 65. [806]+7 errexit, a_AMV_VF_BOOL */
   'e','r','r','e','x','i','t','\0',
   /* 66. [814]+12 errors-limit, a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   'e','r','r','o','r','s','-','l','i','m','i','t','\0',
   /* 67. [827]+6 escape, a_AMV_VF_DEFVAL */
   'e','s','c','a','p','e','\0',
   /* 68. [834]+10 expandaddr */
   'e','x','p','a','n','d','a','d','d','r','\0',
   /* 69. [845]+22 expandaddr-domaincheck, a_AMV_VF_NOTEMPTY */
   'e','x','p','a','n','d','a','d','d','r','-','d','o','m','a','i','n','c','h','e','c','k','\0',
   /* 70. [868]+10 expandargv */
   'e','x','p','a','n','d','a','r','g','v','\0',
   /* 71. [879]+8 features, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'f','e','a','t','u','r','e','s','\0',
   /* 72. [888]+5 flipr, a_AMV_VF_BOOL */
   'f','l','i','p','r','\0',
   /* 73. [894]+6 folder, a_AMV_VF_VIP */
   'f','o','l','d','e','r','\0',
   /* 74. [901]+15 folder-resolved, a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'f','o','l','d','e','r','-','r','e','s','o','l','v','e','d','\0',
   /* 75. [917]+11 folder-hook */
   'f','o','l','d','e','r','-','h','o','o','k','\0',
   /* 76. [929]+11 followup-to, a_AMV_VF_BOOL */
   'f','o','l','l','o','w','u','p','-','t','o','\0',
   /* 77. [941]+18 followup-to-add-cc, a_AMV_VF_BOOL */
   'f','o','l','l','o','w','u','p','-','t','o','-','a','d','d','-','c','c','\0',
   /* 78. [960]+18 followup-to-honour */
   'f','o','l','l','o','w','u','p','-','t','o','-','h','o','n','o','u','r','\0',
   /* 79. [979]+14 forward-add-cc, a_AMV_VF_BOOL */
   'f','o','r','w','a','r','d','-','a','d','d','-','c','c','\0',
   /* 80. [994]+21 forward-as-attachment, a_AMV_VF_BOOL */
   'f','o','r','w','a','r','d','-','a','s','-','a','t','t','a','c','h','m','e','n','t','\0',
   /* 81. [1016]+19 forward-inject-head */
   'f','o','r','w','a','r','d','-','i','n','j','e','c','t','-','h','e','a','d','\0',
   /* 82. [1036]+19 forward-inject-tail */
   'f','o','r','w','a','r','d','-','i','n','j','e','c','t','-','t','a','i','l','\0',
   /* 83. [1056]+4 from, a_AMV_VF_VIP */
   'f','r','o','m','\0',
   /* 84. [1061]+9 fullnames, a_AMV_VF_BOOL */
   'f','u','l','l','n','a','m','e','s','\0',
   /* 85. [1071]+10 fwdheading, a_AMV_VF_OBSOLETE */
   'f','w','d','h','e','a','d','i','n','g','\0',
   /* 86. [1082]+4 HOME, a_AMV_VF_VIP|a_AMV_VF_NODEL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'H','O','M','E','\0',
   /* 87. [1087]+6 header, a_AMV_VF_BOOL|a_AMV_VF_I3VAL */
   'h','e','a','d','e','r','\0',
   /* 88. [1094]+8 headline */
   'h','e','a','d','l','i','n','e','\0',
   /* 89. [1103]+13 headline-bidi */
   'h','e','a','d','l','i','n','e','-','b','i','d','i','\0',
   /* 90. [1117]+14 headline-plain, a_AMV_VF_BOOL */
   'h','e','a','d','l','i','n','e','-','p','l','a','i','n','\0',
   /* 91. [1132]+12 history-file */
   'h','i','s','t','o','r','y','-','f','i','l','e','\0',
   /* 92. [1145]+13 history-gabby */
   'h','i','s','t','o','r','y','-','g','a','b','b','y','\0',
   /* 93. [1159]+21 history-gabby-persist, a_AMV_VF_BOOL */
   'h','i','s','t','o','r','y','-','g','a','b','b','y','-','p','e','r','s','i','s','t','\0',
   /* 94. [1181]+12 history-size, a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   'h','i','s','t','o','r','y','-','s','i','z','e','\0',
   /* 95. [1194]+4 hold, a_AMV_VF_BOOL */
   'h','o','l','d','\0',
   /* 96. [1199]+8 hostname, a_AMV_VF_VIP */
   'h','o','s','t','n','a','m','e','\0',
   /* 97. [1208]+12 idna-disable, a_AMV_VF_BOOL */
   'i','d','n','a','-','d','i','s','a','b','l','e','\0',
   /* 98. [1221]+3 ifs, a_AMV_VF_VIP|a_AMV_VF_DEFVAL */
   'i','f','s','\0',
   /* 99. [1225]+6 ifs-ws, a_AMV_VF_VIP|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_I3VAL */
   'i','f','s','-','w','s','\0',
   /* 100. [1232]+6 ignore, a_AMV_VF_BOOL */
   'i','g','n','o','r','e','\0',
   /* 101. [1239]+9 ignoreeof, a_AMV_VF_BOOL */
   'i','g','n','o','r','e','e','o','f','\0',
   /* 102. [1249]+5 inbox */
   'i','n','b','o','x','\0',
   /* 103. [1255]+12 indentprefix, a_AMV_VF_DEFVAL */
   'i','n','d','e','n','t','p','r','e','f','i','x','\0',
   /* 104. [1268]+4 keep, a_AMV_VF_BOOL */
   'k','e','e','p','\0',
   /* 105. [1273]+19 keep-content-length, a_AMV_VF_BOOL */
   'k','e','e','p','-','c','o','n','t','e','n','t','-','l','e','n','g','t','h','\0',
   /* 106. [1293]+8 keepsave, a_AMV_VF_BOOL */
   'k','e','e','p','s','a','v','e','\0',
   /* 107. [1302]+4 LANG, a_AMV_VF_VIP|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'L','A','N','G','\0',
   /* 108. [1307]+6 LC_ALL, a_AMV_VF_VIP|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'L','C','_','A','L','L','\0',
   /* 109. [1314]+8 LC_CTYPE, a_AMV_VF_VIP|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'L','C','_','C','T','Y','P','E','\0',
   /* 110. [1323]+5 LINES, a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   'L','I','N','E','S','\0',
   /* 111. [1329]+6 LISTER, a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'L','I','S','T','E','R','\0',
   /* 112. [1336]+7 LOGNAME, a_AMV_VF_RDONLY|a_AMV_VF_IMPORT|a_AMV_VF_ENV */
   'L','O','G','N','A','M','E','\0',
   /* 113. [1344]+18 line-editor-config, a_AMV_VF_NOTEMPTY */
   'l','i','n','e','-','e','d','i','t','o','r','-','c','o','n','f','i','g','\0',
   /* 114. [1363]+27 line-editor-cpl-word-breaks, a_AMV_VF_DEFVAL */
   'l','i','n','e','-','e','d','i','t','o','r','-','c','p','l','-','w','o','r','d','-','b','r','e','a','k','s','\0',
   /* 115. [1391]+19 line-editor-disable, a_AMV_VF_BOOL */
   'l','i','n','e','-','e','d','i','t','o','r','-','d','i','s','a','b','l','e','\0',
   /* 116. [1411]+23 line-editor-no-defaults, a_AMV_VF_BOOL */
   'l','i','n','e','-','e','d','i','t','o','r','-','n','o','-','d','e','f','a','u','l','t','s','\0',
   /* 117. [1435]+10 log-prefix, a_AMV_VF_NODEL|a_AMV_VF_I3VAL */
   'l','o','g','-','p','r','e','f','i','x','\0',
   /* 118. [1446]+4 MAIL, a_AMV_VF_ENV */
   'M','A','I','L','\0',
   /* 119. [1451]+8 MAILCAPS, a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_ENV */
   'M','A','I','L','C','A','P','S','\0',
   /* 120. [1460]+6 MAILRC, a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'M','A','I','L','R','C','\0',
   /* 121. [1467]+18 MAILX_NO_SYSTEM_RC, a_AMV_VF_BOOL|a_AMV_VF_IMPORT|a_AMV_VF_ENV */
   'M','A','I','L','X','_','N','O','_','S','Y','S','T','E','M','_','R','C','\0',
   /* 122. [1486]+4 MBOX, a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'M','B','O','X','\0',
   /* 123. [1491]+16 mailbox-resolved, a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS */
   'm','a','i','l','b','o','x','-','r','e','s','o','l','v','e','d','\0',
   /* 124. [1508]+15 mailbox-display, a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS */
   'm','a','i','l','b','o','x','-','d','i','s','p','l','a','y','\0',
   /* 125. [1524]+15 mailcap-disable, a_AMV_VF_BOOL */
   'm','a','i','l','c','a','p','-','d','i','s','a','b','l','e','\0',
   /* 126. [1540]+14 mailx-extra-rc, a_AMV_VF_NOTEMPTY */
   'm','a','i','l','x','-','e','x','t','r','a','-','r','c','\0',
   /* 127. [1555]+12 markanswered, a_AMV_VF_BOOL */
   'm','a','r','k','a','n','s','w','e','r','e','d','\0',
   /* 128. [1568]+16 mbox-fcc-and-pcc, a_AMV_VF_BOOL|a_AMV_VF_I3VAL */
   'm','b','o','x','-','f','c','c','-','a','n','d','-','p','c','c','\0',
   /* 129. [1585]+12 mbox-rfc4155, a_AMV_VF_BOOL */
   'm','b','o','x','-','r','f','c','4','1','5','5','\0',
   /* 130. [1598]+8 memdebug, a_AMV_VF_BOOL|a_AMV_VF_VIP */
   'm','e','m','d','e','b','u','g','\0',
   /* 131. [1607]+18 message-id-disable, a_AMV_VF_BOOL */
   'm','e','s','s','a','g','e','-','i','d','-','d','i','s','a','b','l','e','\0',
   /* 132. [1626]+19 message-inject-head */
   'm','e','s','s','a','g','e','-','i','n','j','e','c','t','-','h','e','a','d','\0',
   /* 133. [1646]+19 message-inject-tail */
   'm','e','s','s','a','g','e','-','i','n','j','e','c','t','-','t','a','i','l','\0',
   /* 134. [1666]+5 metoo, a_AMV_VF_BOOL */
   'm','e','t','o','o','\0',
   /* 135. [1672]+24 mime-allow-text-controls, a_AMV_VF_BOOL */
   'm','i','m','e','-','a','l','l','o','w','-','t','e','x','t','-','c','o','n','t','r','o','l','s','\0',
   /* 136. [1697]+28 mime-alternative-favour-rich, a_AMV_VF_BOOL */
   'm','i','m','e','-','a','l','t','e','r','n','a','t','i','v','e','-','f','a','v','o','u','r','-','r','i','c','h','\0',
   /* 137. [1726]+21 mime-counter-evidence, a_AMV_VF_POSNUM */
   'm','i','m','e','-','c','o','u','n','t','e','r','-','e','v','i','d','e','n','c','e','\0',
   /* 138. [1748]+13 mime-encoding */
   'm','i','m','e','-','e','n','c','o','d','i','n','g','\0',
   /* 139. [1762]+18 mime-force-sendout, a_AMV_VF_BOOL */
   'm','i','m','e','-','f','o','r','c','e','-','s','e','n','d','o','u','t','\0',
   /* 140. [1781]+22 mimetypes-load-control */
   'm','i','m','e','t','y','p','e','s','-','l','o','a','d','-','c','o','n','t','r','o','l','\0',
   /* 141. [1804]+3 mta, a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY */
   'm','t','a','\0',
   /* 142. [1808]+11 mta-aliases, a_AMV_VF_NOTEMPTY */
   'm','t','a','-','a','l','i','a','s','e','s','\0',
   /* 143. [1820]+13 mta-arguments */
   'm','t','a','-','a','r','g','u','m','e','n','t','s','\0',
   /* 144. [1834]+24 mta-no-default-arguments, a_AMV_VF_BOOL */
   'm','t','a','-','n','o','-','d','e','f','a','u','l','t','-','a','r','g','u','m','e','n','t','s','\0',
   /* 145. [1859]+25 mta-no-receiver-arguments, a_AMV_VF_BOOL */
   'm','t','a','-','n','o','-','r','e','c','e','i','v','e','r','-','a','r','g','u','m','e','n','t','s','\0',
   /* 146. [1885]+9 mta-argv0, a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY */
   'm','t','a','-','a','r','g','v','0','\0',
   /* 147. [1895]+10 mta-bcc-ok, a_AMV_VF_BOOL */
   'm','t','a','-','b','c','c','-','o','k','\0',
   /* 148. [1906]+13 NAIL_EXTRA_RC, a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY|a_AMV_VF_OBSOLETE */
   'N','A','I','L','_','E','X','T','R','A','_','R','C','\0',
   /* 149. [1920]+17 NAIL_NO_SYSTEM_RC, a_AMV_VF_BOOL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_OBSOLETE */
   'N','A','I','L','_','N','O','_','S','Y','S','T','E','M','_','R','C','\0',
   /* 150. [1938]+9 NAIL_HEAD, a_AMV_VF_OBSOLETE */
   'N','A','I','L','_','H','E','A','D','\0',
   /* 151. [1948]+13 NAIL_HISTFILE, a_AMV_VF_OBSOLETE */
   'N','A','I','L','_','H','I','S','T','F','I','L','E','\0',
   /* 152. [1962]+13 NAIL_HISTSIZE, a_AMV_VF_NOTEMPTY|a_AMV_VF_NUM|a_AMV_VF_OBSOLETE */
   'N','A','I','L','_','H','I','S','T','S','I','Z','E','\0',
   /* 153. [1976]+9 NAIL_TAIL, a_AMV_VF_OBSOLETE */
   'N','A','I','L','_','T','A','I','L','\0',
   /* 154. [1986]+5 NETRC, a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'N','E','T','R','C','\0',
   /* 155. [1992]+12 netrc-lookup, a_AMV_VF_BOOL|a_AMV_VF_CHAIN */
   'n','e','t','r','c','-','l','o','o','k','u','p','\0',
   /* 156. [2005]+10 netrc-pipe */
   'n','e','t','r','c','-','p','i','p','e','\0',
   /* 157. [2016]+10 newfolders */
   'n','e','w','f','o','l','d','e','r','s','\0',
   /* 158. [2027]+7 newmail */
   'n','e','w','m','a','i','l','\0',
   /* 159. [2035]+18 on-account-cleanup, a_AMV_VF_NOTEMPTY */
   'o','n','-','a','c','c','o','u','n','t','-','c','l','e','a','n','u','p','\0',
   /* 160. [2054]+18 on-compose-cleanup, a_AMV_VF_NOTEMPTY */
   'o','n','-','c','o','m','p','o','s','e','-','c','l','e','a','n','u','p','\0',
   /* 161. [2073]+16 on-compose-enter, a_AMV_VF_NOTEMPTY */
   'o','n','-','c','o','m','p','o','s','e','-','e','n','t','e','r','\0',
   /* 162. [2090]+16 on-compose-leave, a_AMV_VF_NOTEMPTY */
   'o','n','-','c','o','m','p','o','s','e','-','l','e','a','v','e','\0',
   /* 163. [2107]+17 on-compose-splice, a_AMV_VF_NOTEMPTY */
   'o','n','-','c','o','m','p','o','s','e','-','s','p','l','i','c','e','\0',
   /* 164. [2125]+23 on-compose-splice-shell, a_AMV_VF_NOTEMPTY */
   'o','n','-','c','o','m','p','o','s','e','-','s','p','l','i','c','e','-','s','h','e','l','l','\0',
   /* 165. [2149]+19 on-history-addition, a_AMV_VF_NOTEMPTY */
   'o','n','-','h','i','s','t','o','r','y','-','a','d','d','i','t','i','o','n','\0',
   /* 166. [2169]+17 on-main-loop-tick, a_AMV_VF_NOTEMPTY */
   'o','n','-','m','a','i','n','-','l','o','o','p','-','t','i','c','k','\0',
   /* 167. [2187]+15 on-program-exit, a_AMV_VF_NOTEMPTY */
   'o','n','-','p','r','o','g','r','a','m','-','e','x','i','t','\0',
   /* 168. [2203]+17 on-resend-cleanup, a_AMV_VF_NOTEMPTY */
   'o','n','-','r','e','s','e','n','d','-','c','l','e','a','n','u','p','\0',
   /* 169. [2221]+15 on-resend-enter, a_AMV_VF_NOTEMPTY */
   'o','n','-','r','e','s','e','n','d','-','e','n','t','e','r','\0',
   /* 170. [2237]+9 outfolder, a_AMV_VF_BOOL */
   'o','u','t','f','o','l','d','e','r','\0',
   /* 171. [2247]+5 PAGER, a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'P','A','G','E','R','\0',
   /* 172. [2253]+4 PATH, a_AMV_VF_NODEL|a_AMV_VF_IMPORT|a_AMV_VF_ENV */
   'P','A','T','H','\0',
   /* 173. [2258]+15 POSIXLY_CORRECT, a_AMV_VF_BOOL|a_AMV_VF_VIP|a_AMV_VF_IMPORT|a_AMV_VF_ENV */
   'P','O','S','I','X','L','Y','_','C','O','R','R','E','C','T','\0',
   /* 174. [2274]+4 page, a_AMV_VF_BOOL */
   'p','a','g','e','\0',
   /* 175. [2279]+8 password, a_AMV_VF_CHAIN */
   'p','a','s','s','w','o','r','d','\0',
   /* 176. [2288]+7 piperaw, a_AMV_VF_BOOL */
   'p','i','p','e','r','a','w','\0',
   /* 177. [2296]+9 pop3-auth, a_AMV_VF_CHAIN */
   'p','o','p','3','-','a','u','t','h','\0',
   /* 178. [2306]+14 pop3-bulk-load, a_AMV_VF_BOOL */
   'p','o','p','3','-','b','u','l','k','-','l','o','a','d','\0',
   /* 179. [2321]+14 pop3-keepalive, a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   'p','o','p','3','-','k','e','e','p','a','l','i','v','e','\0',
   /* 180. [2336]+12 pop3-no-apop, a_AMV_VF_BOOL|a_AMV_VF_CHAIN */
   'p','o','p','3','-','n','o','-','a','p','o','p','\0',
   /* 181. [2349]+17 pop3-use-starttls, a_AMV_VF_BOOL|a_AMV_VF_CHAIN */
   'p','o','p','3','-','u','s','e','-','s','t','a','r','t','t','l','s','\0',
   /* 182. [2367]+5 posix, a_AMV_VF_BOOL|a_AMV_VF_VIP */
   'p','o','s','i','x','\0',
   /* 183. [2373]+18 print-alternatives, a_AMV_VF_BOOL */
   'p','r','i','n','t','-','a','l','t','e','r','n','a','t','i','v','e','s','\0',
   /* 184. [2392]+6 prompt, a_AMV_VF_I3VAL */
   'p','r','o','m','p','t','\0',
   /* 185. [2399]+7 prompt2, a_AMV_VF_I3VAL */
   'p','r','o','m','p','t','2','\0',
   /* 186. [2407]+5 quiet, a_AMV_VF_BOOL */
   'q','u','i','e','t','\0',
   /* 187. [2413]+5 quote */
   'q','u','o','t','e','\0',
   /* 188. [2419]+12 quote-add-cc, a_AMV_VF_BOOL */
   'q','u','o','t','e','-','a','d','d','-','c','c','\0',
   /* 189. [2432]+19 quote-as-attachment, a_AMV_VF_BOOL */
   'q','u','o','t','e','-','a','s','-','a','t','t','a','c','h','m','e','n','t','\0',
   /* 190. [2452]+11 quote-chars, a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY */
   'q','u','o','t','e','-','c','h','a','r','s','\0',
   /* 191. [2464]+10 quote-fold */
   'q','u','o','t','e','-','f','o','l','d','\0',
   /* 192. [2475]+17 quote-inject-head */
   'q','u','o','t','e','-','i','n','j','e','c','t','-','h','e','a','d','\0',
   /* 193. [2493]+17 quote-inject-tail */
   'q','u','o','t','e','-','i','n','j','e','c','t','-','t','a','i','l','\0',
   /* 194. [2511]+17 r-option-implicit, a_AMV_VF_BOOL */
   'r','-','o','p','t','i','o','n','-','i','m','p','l','i','c','i','t','\0',
   /* 195. [2529]+16 recipients-in-cc, a_AMV_VF_BOOL */
   'r','e','c','i','p','i','e','n','t','s','-','i','n','-','c','c','\0',
   /* 196. [2546]+6 record */
   'r','e','c','o','r','d','\0',
   /* 197. [2553]+12 record-files, a_AMV_VF_BOOL */
   'r','e','c','o','r','d','-','f','i','l','e','s','\0',
   /* 198. [2566]+13 record-resent, a_AMV_VF_BOOL */
   'r','e','c','o','r','d','-','r','e','s','e','n','t','\0',
   /* 199. [2580]+21 reply-in-same-charset, a_AMV_VF_BOOL */
   'r','e','p','l','y','-','i','n','-','s','a','m','e','-','c','h','a','r','s','e','t','\0',
   /* 200. [2602]+13 reply-strings */
   'r','e','p','l','y','-','s','t','r','i','n','g','s','\0',
   /* 201. [2616]+7 replyto, a_AMV_VF_NOTEMPTY|a_AMV_VF_OBSOLETE */
   'r','e','p','l','y','t','o','\0',
   /* 202. [2624]+8 reply-to, a_AMV_VF_NOTEMPTY */
   'r','e','p','l','y','-','t','o','\0',
   /* 203. [2633]+15 reply-to-honour */
   'r','e','p','l','y','-','t','o','-','h','o','n','o','u','r','\0',
   /* 204. [2649]+16 reply-to-swap-in */
   'r','e','p','l','y','-','t','o','-','s','w','a','p','-','i','n','\0',
   /* 205. [2666]+17 rfc822-body-from_, a_AMV_VF_BOOL */
   'r','f','c','8','2','2','-','b','o','d','y','-','f','r','o','m','_','\0',
   /* 206. [2684]+5 SHELL, a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'S','H','E','L','L','\0',
   /* 207. [2690]+5 SYSV3, a_AMV_VF_BOOL|a_AMV_VF_ENV|a_AMV_VF_OBSOLETE */
   'S','Y','S','V','3','\0',
   /* 208. [2696]+4 save, a_AMV_VF_BOOL|a_AMV_VF_I3VAL */
   's','a','v','e','\0',
   /* 209. [2701]+6 screen, a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   's','c','r','e','e','n','\0',
   /* 210. [2708]+13 searchheaders, a_AMV_VF_BOOL */
   's','e','a','r','c','h','h','e','a','d','e','r','s','\0',
   /* 211. [2722]+12 sendcharsets, a_AMV_VF_VIP */
   's','e','n','d','c','h','a','r','s','e','t','s','\0',
   /* 212. [2735]+28 sendcharsets-else-ttycharset, a_AMV_VF_BOOL */
   's','e','n','d','c','h','a','r','s','e','t','s','-','e','l','s','e','-','t','t','y','c','h','a','r','s','e','t','\0',
   /* 213. [2764]+6 sender, a_AMV_VF_VIP */
   's','e','n','d','e','r','\0',
   /* 214. [2771]+8 sendmail, a_AMV_VF_OBSOLETE */
   's','e','n','d','m','a','i','l','\0',
   /* 215. [2780]+18 sendmail-arguments, a_AMV_VF_OBSOLETE */
   's','e','n','d','m','a','i','l','-','a','r','g','u','m','e','n','t','s','\0',
   /* 216. [2799]+29 sendmail-no-default-arguments, a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE */
   's','e','n','d','m','a','i','l','-','n','o','-','d','e','f','a','u','l','t','-','a','r','g','u','m','e','n','t','s','\0',
   /* 217. [2829]+17 sendmail-progname, a_AMV_VF_OBSOLETE */
   's','e','n','d','m','a','i','l','-','p','r','o','g','n','a','m','e','\0',
   /* 218. [2847]+8 sendwait, a_AMV_VF_I3VAL */
   's','e','n','d','w','a','i','t','\0',
   /* 219. [2856]+8 showlast, a_AMV_VF_BOOL */
   's','h','o','w','l','a','s','t','\0',
   /* 220. [2865]+8 showname, a_AMV_VF_BOOL */
   's','h','o','w','n','a','m','e','\0',
   /* 221. [2874]+6 showto, a_AMV_VF_BOOL */
   's','h','o','w','t','o','\0',
   /* 222. [2881]+4 Sign */
   'S','i','g','n','\0',
   /* 223. [2886]+4 sign */
   's','i','g','n','\0',
   /* 224. [2891]+9 signature, a_AMV_VF_OBSOLETE */
   's','i','g','n','a','t','u','r','e','\0',
   /* 225. [2901]+13 skipemptybody, a_AMV_VF_BOOL|a_AMV_VF_VIP */
   's','k','i','p','e','m','p','t','y','b','o','d','y','\0',
   /* 226. [2915]+12 smime-ca-dir */
   's','m','i','m','e','-','c','a','-','d','i','r','\0',
   /* 227. [2928]+13 smime-ca-file */
   's','m','i','m','e','-','c','a','-','f','i','l','e','\0',
   /* 228. [2942]+14 smime-ca-flags */
   's','m','i','m','e','-','c','a','-','f','l','a','g','s','\0',
   /* 229. [2957]+20 smime-ca-no-defaults, a_AMV_VF_BOOL */
   's','m','i','m','e','-','c','a','-','n','o','-','d','e','f','a','u','l','t','s','\0',
   /* 230. [2978]+12 smime-cipher, a_AMV_VF_CHAIN */
   's','m','i','m','e','-','c','i','p','h','e','r','\0',
   /* 231. [2991]+13 smime-crl-dir */
   's','m','i','m','e','-','c','r','l','-','d','i','r','\0',
   /* 232. [3005]+14 smime-crl-file */
   's','m','i','m','e','-','c','r','l','-','f','i','l','e','\0',
   /* 233. [3020]+13 smime-encrypt, a_AMV_VF_CHAIN */
   's','m','i','m','e','-','e','n','c','r','y','p','t','\0',
   /* 234. [3034]+22 smime-force-encryption, a_AMV_VF_BOOL */
   's','m','i','m','e','-','f','o','r','c','e','-','e','n','c','r','y','p','t','i','o','n','\0',
   /* 235. [3057]+19 smime-no-default-ca, a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE */
   's','m','i','m','e','-','n','o','-','d','e','f','a','u','l','t','-','c','a','\0',
   /* 236. [3077]+10 smime-sign, a_AMV_VF_BOOL */
   's','m','i','m','e','-','s','i','g','n','\0',
   /* 237. [3088]+15 smime-sign-cert, a_AMV_VF_CHAIN */
   's','m','i','m','e','-','s','i','g','n','-','c','e','r','t','\0',
   /* 238. [3104]+17 smime-sign-digest, a_AMV_VF_CHAIN */
   's','m','i','m','e','-','s','i','g','n','-','d','i','g','e','s','t','\0',
   /* 239. [3122]+24 smime-sign-include-certs, a_AMV_VF_CHAIN */
   's','m','i','m','e','-','s','i','g','n','-','i','n','c','l','u','d','e','-','c','e','r','t','s','\0',
   /* 240. [3147]+25 smime-sign-message-digest, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','m','i','m','e','-','s','i','g','n','-','m','e','s','s','a','g','e','-','d','i','g','e','s','t','\0',
   /* 241. [3173]+4 smtp, a_AMV_VF_OBSOLETE */
   's','m','t','p','\0',
   /* 242. [3178]+9 smtp-auth, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','m','t','p','-','a','u','t','h','\0',
   /* 243. [3188]+18 smtp-auth-password, a_AMV_VF_OBSOLETE */
   's','m','t','p','-','a','u','t','h','-','p','a','s','s','w','o','r','d','\0',
   /* 244. [3207]+14 smtp-auth-user, a_AMV_VF_OBSOLETE */
   's','m','t','p','-','a','u','t','h','-','u','s','e','r','\0',
   /* 245. [3222]+11 smtp-config, a_AMV_VF_CHAIN */
   's','m','t','p','-','c','o','n','f','i','g','\0',
   /* 246. [3234]+13 smtp-hostname, a_AMV_VF_VIP|a_AMV_VF_CHAIN */
   's','m','t','p','-','h','o','s','t','n','a','m','e','\0',
   /* 247. [3248]+17 smtp-use-starttls, a_AMV_VF_BOOL|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','m','t','p','-','u','s','e','-','s','t','a','r','t','t','l','s','\0',
   /* 248. [3266]+12 SOCKS5_PROXY, a_AMV_VF_VIP|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'S','O','C','K','S','5','_','P','R','O','X','Y','\0',
   /* 249. [3279]+17 SOURCE_DATE_EPOCH, a_AMV_VF_RDONLY|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   'S','O','U','R','C','E','_','D','A','T','E','_','E','P','O','C','H','\0',
   /* 250. [3297]+22 socket-connect-timeout, a_AMV_VF_POSNUM */
   's','o','c','k','e','t','-','c','o','n','n','e','c','t','-','t','i','m','e','o','u','t','\0',
   /* 251. [3320]+11 socks-proxy, a_AMV_VF_VIP|a_AMV_VF_NOTEMPTY|a_AMV_VF_CHAIN */
   's','o','c','k','s','-','p','r','o','x','y','\0',
   /* 252. [3332]+14 spam-interface */
   's','p','a','m','-','i','n','t','e','r','f','a','c','e','\0',
   /* 253. [3347]+12 spam-maxsize, a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM */
   's','p','a','m','-','m','a','x','s','i','z','e','\0',
   /* 254. [3360]+13 spamc-command */
   's','p','a','m','c','-','c','o','m','m','a','n','d','\0',
   /* 255. [3374]+15 spamc-arguments */
   's','p','a','m','c','-','a','r','g','u','m','e','n','t','s','\0',
   /* 256. [3390]+10 spamc-user */
   's','p','a','m','c','-','u','s','e','r','\0',
   /* 257. [3401]+14 spamfilter-ham */
   's','p','a','m','f','i','l','t','e','r','-','h','a','m','\0',
   /* 258. [3416]+16 spamfilter-noham */
   's','p','a','m','f','i','l','t','e','r','-','n','o','h','a','m','\0',
   /* 259. [3433]+17 spamfilter-nospam */
   's','p','a','m','f','i','l','t','e','r','-','n','o','s','p','a','m','\0',
   /* 260. [3451]+15 spamfilter-rate */
   's','p','a','m','f','i','l','t','e','r','-','r','a','t','e','\0',
   /* 261. [3467]+25 spamfilter-rate-scanscore */
   's','p','a','m','f','i','l','t','e','r','-','r','a','t','e','-','s','c','a','n','s','c','o','r','e','\0',
   /* 262. [3493]+15 spamfilter-spam */
   's','p','a','m','f','i','l','t','e','r','-','s','p','a','m','\0',
   /* 263. [3509]+10 ssl-ca-dir, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','c','a','-','d','i','r','\0',
   /* 264. [3520]+11 ssl-ca-file, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','c','a','-','f','i','l','e','\0',
   /* 265. [3532]+12 ssl-ca-flags, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','c','a','-','f','l','a','g','s','\0',
   /* 266. [3545]+18 ssl-ca-no-defaults, a_AMV_VF_BOOL|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','c','a','-','n','o','-','d','e','f','a','u','l','t','s','\0',
   /* 267. [3564]+8 ssl-cert, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','c','e','r','t','\0',
   /* 268. [3573]+15 ssl-cipher-list, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','c','i','p','h','e','r','-','l','i','s','t','\0',
   /* 269. [3589]+15 ssl-config-file, a_AMV_VF_OBSOLETE */
   's','s','l','-','c','o','n','f','i','g','-','f','i','l','e','\0',
   /* 270. [3605]+17 ssl-config-module, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','c','o','n','f','i','g','-','m','o','d','u','l','e','\0',
   /* 271. [3623]+16 ssl-config-pairs, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','c','o','n','f','i','g','-','p','a','i','r','s','\0',
   /* 272. [3640]+10 ssl-curves, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','c','u','r','v','e','s','\0',
   /* 273. [3651]+11 ssl-crl-dir, a_AMV_VF_OBSOLETE */
   's','s','l','-','c','r','l','-','d','i','r','\0',
   /* 274. [3663]+12 ssl-crl-file, a_AMV_VF_OBSOLETE */
   's','s','l','-','c','r','l','-','f','i','l','e','\0',
   /* 275. [3676]+12 ssl-features, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_OBSOLETE */
   's','s','l','-','f','e','a','t','u','r','e','s','\0',
   /* 276. [3689]+7 ssl-key, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','k','e','y','\0',
   /* 277. [3697]+10 ssl-method, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','m','e','t','h','o','d','\0',
   /* 278. [3708]+17 ssl-no-default-ca, a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE */
   's','s','l','-','n','o','-','d','e','f','a','u','l','t','-','c','a','\0',
   /* 279. [3726]+12 ssl-protocol, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','p','r','o','t','o','c','o','l','\0',
   /* 280. [3739]+12 ssl-rand-egd, a_AMV_VF_OBSOLETE */
   's','s','l','-','r','a','n','d','-','e','g','d','\0',
   /* 281. [3752]+13 ssl-rand-file, a_AMV_VF_OBSOLETE */
   's','s','l','-','r','a','n','d','-','f','i','l','e','\0',
   /* 282. [3766]+10 ssl-verify, a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE */
   's','s','l','-','v','e','r','i','f','y','\0',
   /* 283. [3777]+10 stealthmua */
   's','t','e','a','l','t','h','m','u','a','\0',
   /* 284. [3788]+13 system-mailrc, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   's','y','s','t','e','m','-','m','a','i','l','r','c','\0',
   /* 285. [3802]+4 TERM, a_AMV_VF_ENV */
   'T','E','R','M','\0',
   /* 286. [3807]+6 TMPDIR, a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'T','M','P','D','I','R','\0',
   /* 287. [3814]+7 termcap */
   't','e','r','m','c','a','p','\0',
   /* 288. [3822]+15 termcap-ca-mode, a_AMV_VF_BOOL */
   't','e','r','m','c','a','p','-','c','a','-','m','o','d','e','\0',
   /* 289. [3838]+15 termcap-disable, a_AMV_VF_BOOL */
   't','e','r','m','c','a','p','-','d','i','s','a','b','l','e','\0',
   /* 290. [3854]+10 tls-ca-dir, a_AMV_VF_CHAIN */
   't','l','s','-','c','a','-','d','i','r','\0',
   /* 291. [3865]+11 tls-ca-file, a_AMV_VF_CHAIN */
   't','l','s','-','c','a','-','f','i','l','e','\0',
   /* 292. [3877]+12 tls-ca-flags, a_AMV_VF_CHAIN */
   't','l','s','-','c','a','-','f','l','a','g','s','\0',
   /* 293. [3890]+18 tls-ca-no-defaults, a_AMV_VF_BOOL|a_AMV_VF_CHAIN */
   't','l','s','-','c','a','-','n','o','-','d','e','f','a','u','l','t','s','\0',
   /* 294. [3909]+15 tls-config-file */
   't','l','s','-','c','o','n','f','i','g','-','f','i','l','e','\0',
   /* 295. [3925]+17 tls-config-module, a_AMV_VF_CHAIN */
   't','l','s','-','c','o','n','f','i','g','-','m','o','d','u','l','e','\0',
   /* 296. [3943]+16 tls-config-pairs, a_AMV_VF_CHAIN */
   't','l','s','-','c','o','n','f','i','g','-','p','a','i','r','s','\0',
   /* 297. [3960]+11 tls-crl-dir */
   't','l','s','-','c','r','l','-','d','i','r','\0',
   /* 298. [3972]+12 tls-crl-file */
   't','l','s','-','c','r','l','-','f','i','l','e','\0',
   /* 299. [3985]+12 tls-features, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   't','l','s','-','f','e','a','t','u','r','e','s','\0',
   /* 300. [3998]+15 tls-fingerprint, a_AMV_VF_CHAIN */
   't','l','s','-','f','i','n','g','e','r','p','r','i','n','t','\0',
   /* 301. [4014]+22 tls-fingerprint-digest, a_AMV_VF_CHAIN */
   't','l','s','-','f','i','n','g','e','r','p','r','i','n','t','-','d','i','g','e','s','t','\0',
   /* 302. [4037]+13 tls-rand-file */
   't','l','s','-','r','a','n','d','-','f','i','l','e','\0',
   /* 303. [4051]+10 tls-verify, a_AMV_VF_CHAIN */
   't','l','s','-','v','e','r','i','f','y','\0',
   /* 304. [4062]+8 toplines, a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_NUM */
   't','o','p','l','i','n','e','s','\0',
   /* 305. [4071]+10 topsqueeze, a_AMV_VF_BOOL */
   't','o','p','s','q','u','e','e','z','e','\0',
   /* 306. [4082]+10 ttycharset, a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY */
   't','t','y','c','h','a','r','s','e','t','\0',
   /* 307. [4093]+15 typescript-mode, a_AMV_VF_BOOL|a_AMV_VF_VIP */
   't','y','p','e','s','c','r','i','p','t','-','m','o','d','e','\0',
   /* 308. [4109]+4 USER, a_AMV_VF_RDONLY|a_AMV_VF_IMPORT|a_AMV_VF_ENV */
   'U','S','E','R','\0',
   /* 309. [4114]+5 umask, a_AMV_VF_VIP|a_AMV_VF_NODEL|a_AMV_VF_I3VAL|a_AMV_VF_POSNUM */
   'u','m','a','s','k','\0',
   /* 310. [4120]+4 user, a_AMV_VF_NOTEMPTY|a_AMV_VF_CHAIN */
   'u','s','e','r','\0',
   /* 311. [4125]+6 VISUAL, a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY */
   'V','I','S','U','A','L','\0',
   /* 312. [4132]+10 v15-compat, a_AMV_VF_I3VAL */
   'v','1','5','-','c','o','m','p','a','t','\0',
   /* 313. [4143]+7 verbose, a_AMV_VF_VIP|a_AMV_VF_POSNUM */
   'v','e','r','b','o','s','e','\0',
   /* 314. [4151]+7 version, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'v','e','r','s','i','o','n','\0',
   /* 315. [4159]+12 version-date, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL */
   'v','e','r','s','i','o','n','-','d','a','t','e','\0',
   /* 316. [4172]+14 version-hexnum, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM */
   'v','e','r','s','i','o','n','-','h','e','x','n','u','m','\0',
   /* 317. [4187]+13 version-major, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM */
   'v','e','r','s','i','o','n','-','m','a','j','o','r','\0',
   /* 318. [4201]+13 version-minor, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM */
   'v','e','r','s','i','o','n','-','m','i','n','o','r','\0',
   /* 319. [4215]+14 version-update, a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM */
   'v','e','r','s','i','o','n','-','u','p','d','a','t','e','\0',
   /* 320. [4230]+15 writebackedited, a_AMV_VF_BOOL */
   'w','r','i','t','e','b','a','c','k','e','d','i','t','e','d','\0',
   /* 321. [4246]+12 disconnected, a_AMV_VF_BOOL|a_AMV_VF_CHAIN */
   'd','i','s','c','o','n','n','e','c','t','e','d','\0',
   /* 322. [4259]+9 imap-auth, a_AMV_VF_CHAIN */
   'i','m','a','p','-','a','u','t','h','\0',
   /* 323. [4269]+10 imap-cache */
   'i','m','a','p','-','c','a','c','h','e','\0',
   /* 324. [4280]+10 imap-delim, a_AMV_VF_CHAIN */
   'i','m','a','p','-','d','e','l','i','m','\0',
   /* 325. [4291]+14 imap-keepalive, a_AMV_VF_CHAIN */
   'i','m','a','p','-','k','e','e','p','a','l','i','v','e','\0',
   /* 326. [4306]+15 imap-list-depth */
   'i','m','a','p','-','l','i','s','t','-','d','e','p','t','h','\0',
   /* 327. [4322]+17 imap-use-starttls, a_AMV_VF_BOOL|a_AMV_VF_CHAIN */
   'i','m','a','p','-','u','s','e','-','s','t','a','r','t','t','l','s','\0',
   /* 328. [4340]+13 _S_MAILX_TEST, a_AMV_VF_ENV */
   '_','S','_','M','A','I','L','X','_','T','E','S','T','\0',
};
#define a_AMV_VAR_NAME_KEY_MAXOFF 4354u
#define a_AMV_VAR_HAS_OBSOLETE

CTA(a_AMV_VF_NONE == 0, "Value not 0 as expected");
static struct a_amv_var_map const a_amv_var_map[] = {
   {227278652u, 0u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS},   /* --special-param */
   {154495572u, 16u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS},   /* ? */
   {80927451u, 18u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS},   /* ! */
   {3357062669u, 20u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS},   /* account */
   {493847641u, 28u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* add-file-recipients */
   {3300482900u, 48u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* agent-shell-lookup */
   {494283953u, 67u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* allnet */
   {1058320012u, 74u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* append */
   {2551535105u, 81u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_VIP},   /* ask */
   {3811864832u, 85u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* askatend */
   {996153470u, 94u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* askattach */
   {1888769187u, 104u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* askbcc */
   {116464337u, 111u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* askcc */
   {2284472721u, 117u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* asksign */
   {3082104315u, 125u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* asksend */
   {311620u, 133u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_I3VAL},   /* asksub */
   {745929243u, 140u, a_AMV_VF_NONE},   /* attrlist */
   {4253309083u, 149u, a_AMV_VF_NONE},   /* autobcc */
   {1364365036u, 157u, a_AMV_VF_NONE},   /* autocc */
   {3614598233u, 164u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* autocollapse */
   {1227119359u, 177u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* autoprint */
   {2751932733u, 187u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE},   /* autothread */
   {795112500u, 198u, a_AMV_VF_NONE},   /* autosort */
   {2505240952u, 207u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* bang */
   {2561950027u, 212u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM|a_AMV_VF_OBSOLETE},   /* bind-timeout */
   {3708435556u, 225u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* bind-inter-byte-timeout */
   {3166102662u, 249u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* bind-inter-key-timeout */
   {2594579305u, 272u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE},   /* bsdannounce */
   {3899593563u, 284u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* bsdcompat */
   {4175238939u, 294u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* bsdflags */
   {544406618u, 303u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* bsdheadline */
   {3124538195u, 315u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* bsdmsgs */
   {4225922782u, 323u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* bsdorder */
   {4282337783u, 332u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* build-cc */
   {580749460u, 341u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* build-ld */
   {855442780u, 350u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* build-os */
   {826549826u, 359u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* build-rest */
   {2160670167u, 370u, a_AMV_VF_NONE|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* COLUMNS */
   {1152129485u, 378u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY},   /* charset-7bit */
   {3559906218u, 391u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY},   /* charset-8bit */
   {2813999997u, 404u, a_AMV_VF_NONE|a_AMV_VF_VIP},   /* charset-unknown-8bit */
   {3267913060u, 425u, a_AMV_VF_NONE},   /* cmd */
   {287190100u, 429u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* colour-disable */
   {846327017u, 444u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* colour-pager */
   {1122098125u, 457u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* contact-mail */
   {1124592011u, 470u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* contact-web */
   {2597875993u, 482u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL},   /* content-description-forwarded-message */
   {1060377975u, 520u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL},   /* content-description-quote-attachment */
   {3459029433u, 557u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL},   /* content-description-smime-message */
   {2186292469u, 591u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL},   /* content-description-smime-signature */
   {2999592795u, 627u, a_AMV_VF_NONE|a_AMV_VF_POSNUM},   /* crt */
   {2781333397u, 631u, a_AMV_VF_NONE|a_AMV_VF_VIP},   /* customhdr */
   {2415640462u, 641u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* DEAD */
   {1827964010u, 646u, a_AMV_VF_NONE|a_AMV_VF_I3VAL},   /* datefield */
   {393145609u, 656u, a_AMV_VF_NONE|a_AMV_VF_I3VAL},   /* datefield-markout-older */
   {3577320874u, 680u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_VIP},   /* debug */
   {2967068228u, 686u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* disposition-notification-send */
   {1214666681u, 716u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* dot */
   {160284180u, 720u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* dotlock-disable */
   {1694953629u, 736u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE},   /* dotlock-ignore-error */
   {1242446766u, 757u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* EDITOR */
   {1594887356u, 764u, a_AMV_VF_NONE},   /* editalong */
   {3883110174u, 774u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* editheaders */
   {2988505335u, 786u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* emptystart */
   {3787987885u, 797u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* encoding */
   {558368469u, 806u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* errexit */
   {2009839120u, 814u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* errors-limit */
   {226969255u, 827u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL},   /* escape */
   {290884965u, 834u, a_AMV_VF_NONE},   /* expandaddr */
   {1137944571u, 845u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* expandaddr-domaincheck */
   {246331225u, 868u, a_AMV_VF_NONE},   /* expandargv */
   {2405915007u, 879u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* features */
   {396387274u, 888u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* flipr */
   {1247301214u, 894u, a_AMV_VF_NONE|a_AMV_VF_VIP},   /* folder */
   {380489737u, 901u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* folder-resolved */
   {3313520922u, 917u, a_AMV_VF_NONE},   /* folder-hook */
   {724424027u, 929u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* followup-to */
   {207519379u, 941u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* followup-to-add-cc */
   {4130486046u, 960u, a_AMV_VF_NONE},   /* followup-to-honour */
   {1845222365u, 979u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* forward-add-cc */
   {1502086073u, 994u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* forward-as-attachment */
   {3821632635u, 1016u, a_AMV_VF_NONE},   /* forward-inject-head */
   {2452299938u, 1036u, a_AMV_VF_NONE},   /* forward-inject-tail */
   {602154724u, 1056u, a_AMV_VF_NONE|a_AMV_VF_VIP},   /* from */
   {3763021371u, 1061u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* fullnames */
   {1982641597u, 1071u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* fwdheading */
   {2741985269u, 1082u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_NODEL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* HOME */
   {64545433u, 1087u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_I3VAL},   /* header */
   {3501927842u, 1094u, a_AMV_VF_NONE},   /* headline */
   {1804975779u, 1103u, a_AMV_VF_NONE},   /* headline-bidi */
   {1481160096u, 1117u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* headline-plain */
   {912008308u, 1132u, a_AMV_VF_NONE},   /* history-file */
   {3026632813u, 1145u, a_AMV_VF_NONE},   /* history-gabby */
   {2385770127u, 1159u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* history-gabby-persist */
   {525831433u, 1181u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* history-size */
   {2672153034u, 1194u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* hold */
   {2616319247u, 1199u, a_AMV_VF_NONE|a_AMV_VF_VIP},   /* hostname */
   {978281147u, 1208u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* idna-disable */
   {1104992522u, 1221u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_DEFVAL},   /* ifs */
   {3356804030u, 1225u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_I3VAL},   /* ifs-ws */
   {728948543u, 1232u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* ignore */
   {2906377970u, 1239u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* ignoreeof */
   {2604688712u, 1249u, a_AMV_VF_NONE},   /* inbox */
   {1338595061u, 1255u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL},   /* indentprefix */
   {143835737u, 1268u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* keep */
   {4104264131u, 1273u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* keep-content-length */
   {174649434u, 1293u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* keepsave */
   {2145171579u, 1302u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* LANG */
   {1678977712u, 1307u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* LC_ALL */
   {1182282912u, 1314u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* LC_CTYPE */
   {2376678931u, 1323u, a_AMV_VF_NONE|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* LINES */
   {1848015380u, 1329u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* LISTER */
   {3871590672u, 1336u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_IMPORT|a_AMV_VF_ENV},   /* LOGNAME */
   {3705547024u, 1344u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* line-editor-config */
   {3059025987u, 1363u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL},   /* line-editor-cpl-word-breaks */
   {3293963057u, 1391u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* line-editor-disable */
   {3853763107u, 1411u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* line-editor-no-defaults */
   {1789070192u, 1435u, a_AMV_VF_NONE|a_AMV_VF_NODEL|a_AMV_VF_I3VAL},   /* log-prefix */
   {1789157842u, 1446u, a_AMV_VF_NONE|a_AMV_VF_ENV},   /* MAIL */
   {2736404651u, 1451u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_ENV},   /* MAILCAPS */
   {3252715507u, 1460u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* MAILRC */
   {3506381864u, 1467u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_IMPORT|a_AMV_VF_ENV},   /* MAILX_NO_SYSTEM_RC */
   {81016594u, 1486u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* MBOX */
   {431868467u, 1491u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS},   /* mailbox-resolved */
   {3586483916u, 1508u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_NOLOPTS},   /* mailbox-display */
   {3619987079u, 1524u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* mailcap-disable */
   {1809788732u, 1540u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* mailx-extra-rc */
   {3344360316u, 1555u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* markanswered */
   {97960896u, 1568u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_I3VAL},   /* mbox-fcc-and-pcc */
   {1206644946u, 1585u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* mbox-rfc4155 */
   {411705792u, 1598u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_VIP},   /* memdebug */
   {2924780567u, 1607u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* message-id-disable */
   {3508650772u, 1626u, a_AMV_VF_NONE},   /* message-inject-head */
   {2318901230u, 1646u, a_AMV_VF_NONE},   /* message-inject-tail */
   {3755204636u, 1666u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* metoo */
   {1123775568u, 1672u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* mime-allow-text-controls */
   {1016573875u, 1697u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* mime-alternative-favour-rich */
   {1894749336u, 1726u, a_AMV_VF_NONE|a_AMV_VF_POSNUM},   /* mime-counter-evidence */
   {7077405u, 1748u, a_AMV_VF_NONE},   /* mime-encoding */
   {212277572u, 1762u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* mime-force-sendout */
   {3037097698u, 1781u, a_AMV_VF_NONE},   /* mimetypes-load-control */
   {553443582u, 1804u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY},   /* mta */
   {832650830u, 1808u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* mta-aliases */
   {2950745266u, 1820u, a_AMV_VF_NONE},   /* mta-arguments */
   {3777230887u, 1834u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* mta-no-default-arguments */
   {1537483713u, 1859u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* mta-no-receiver-arguments */
   {2122434769u, 1885u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY},   /* mta-argv0 */
   {3661122784u, 1895u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* mta-bcc-ok */
   {3872053044u, 1906u, a_AMV_VF_NONE|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY|a_AMV_VF_OBSOLETE},   /* NAIL_EXTRA_RC */
   {297169422u, 1920u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_OBSOLETE},   /* NAIL_NO_SYSTEM_RC */
   {1607860199u, 1938u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* NAIL_HEAD */
   {2276529140u, 1948u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* NAIL_HISTFILE */
   {3334752474u, 1962u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_NUM|a_AMV_VF_OBSOLETE},   /* NAIL_HISTSIZE */
   {1983079716u, 1976u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* NAIL_TAIL */
   {2020589051u, 1986u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* NETRC */
   {1260217930u, 1992u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_CHAIN},   /* netrc-lookup */
   {3886637952u, 2005u, a_AMV_VF_NONE},   /* netrc-pipe */
   {3651172215u, 2016u, a_AMV_VF_NONE},   /* newfolders */
   {3304640034u, 2027u, a_AMV_VF_NONE},   /* newmail */
   {117356079u, 2035u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-account-cleanup */
   {4290007558u, 2054u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-compose-cleanup */
   {293825268u, 2073u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-compose-enter */
   {2131049871u, 2090u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-compose-leave */
   {3562380821u, 2107u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-compose-splice */
   {3452672776u, 2125u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-compose-splice-shell */
   {1488358487u, 2149u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-history-addition */
   {3412211600u, 2169u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-main-loop-tick */
   {395906010u, 2187u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-program-exit */
   {1767855548u, 2203u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-resend-cleanup */
   {2401366305u, 2221u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* on-resend-enter */
   {416513343u, 2237u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* outfolder */
   {1489818949u, 2247u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* PAGER */
   {2822297945u, 2253u, a_AMV_VF_NONE|a_AMV_VF_NODEL|a_AMV_VF_IMPORT|a_AMV_VF_ENV},   /* PATH */
   {2133454918u, 2258u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_VIP|a_AMV_VF_IMPORT|a_AMV_VF_ENV},   /* POSIXLY_CORRECT */
   {110139073u, 2274u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* page */
   {236033362u, 2279u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* password */
   {1184554264u, 2288u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* piperaw */
   {959912200u, 2296u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* pop3-auth */
   {2157156237u, 2306u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* pop3-bulk-load */
   {3679046711u, 2321u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* pop3-keepalive */
   {1128676729u, 2336u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_CHAIN},   /* pop3-no-apop */
   {403462699u, 2349u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_CHAIN},   /* pop3-use-starttls */
   {2340434703u, 2367u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_VIP},   /* posix */
   {909397219u, 2373u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* print-alternatives */
   {3753422504u, 2392u, a_AMV_VF_NONE|a_AMV_VF_I3VAL},   /* prompt */
   {1957394514u, 2399u, a_AMV_VF_NONE|a_AMV_VF_I3VAL},   /* prompt2 */
   {149149615u, 2407u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* quiet */
   {3721493487u, 2413u, a_AMV_VF_NONE},   /* quote */
   {366442025u, 2419u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* quote-add-cc */
   {1890299439u, 2432u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* quote-as-attachment */
   {4044677414u, 2452u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY},   /* quote-chars */
   {3595968213u, 2464u, a_AMV_VF_NONE},   /* quote-fold */
   {2640088545u, 2475u, a_AMV_VF_NONE},   /* quote-inject-head */
   {2904204181u, 2493u, a_AMV_VF_NONE},   /* quote-inject-tail */
   {1640115048u, 2511u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* r-option-implicit */
   {188553526u, 2529u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* recipients-in-cc */
   {540723528u, 2546u, a_AMV_VF_NONE},   /* record */
   {146539205u, 2553u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* record-files */
   {2425465309u, 2566u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* record-resent */
   {1513358607u, 2580u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* reply-in-same-charset */
   {1900410726u, 2602u, a_AMV_VF_NONE},   /* reply-strings */
   {2583631056u, 2616u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_OBSOLETE},   /* replyto */
   {1151099134u, 2624u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY},   /* reply-to */
   {2823711003u, 2633u, a_AMV_VF_NONE},   /* reply-to-honour */
   {1277335386u, 2649u, a_AMV_VF_NONE},   /* reply-to-swap-in */
   {3620202244u, 2666u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* rfc822-body-from_ */
   {1938020952u, 2684u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* SHELL */
   {4069714370u, 2690u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_ENV|a_AMV_VF_OBSOLETE},   /* SYSV3 */
   {3498694618u, 2696u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_I3VAL},   /* save */
   {3962019339u, 2701u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* screen */
   {1130371609u, 2708u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* searchheaders */
   {968926480u, 2722u, a_AMV_VF_NONE|a_AMV_VF_VIP},   /* sendcharsets */
   {760633097u, 2735u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* sendcharsets-else-ttycharset */
   {504631978u, 2764u, a_AMV_VF_NONE|a_AMV_VF_VIP},   /* sender */
   {856236114u, 2771u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* sendmail */
   {3085354123u, 2780u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* sendmail-arguments */
   {1325127300u, 2799u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE},   /* sendmail-no-default-arguments */
   {3864687553u, 2829u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* sendmail-progname */
   {1977567474u, 2847u, a_AMV_VF_NONE|a_AMV_VF_I3VAL},   /* sendwait */
   {3980879360u, 2856u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* showlast */
   {4203664219u, 2865u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* showname */
   {3064935001u, 2874u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* showto */
   {833163053u, 2881u, a_AMV_VF_NONE},   /* Sign */
   {1713520988u, 2886u, a_AMV_VF_NONE},   /* sign */
   {2783766075u, 2891u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* signature */
   {534091439u, 2901u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_VIP},   /* skipemptybody */
   {135477722u, 2915u, a_AMV_VF_NONE},   /* smime-ca-dir */
   {946781610u, 2928u, a_AMV_VF_NONE},   /* smime-ca-file */
   {1507345877u, 2942u, a_AMV_VF_NONE},   /* smime-ca-flags */
   {2951976498u, 2957u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* smime-ca-no-defaults */
   {1752439545u, 2978u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* smime-cipher */
   {102302029u, 2991u, a_AMV_VF_NONE},   /* smime-crl-dir */
   {86428004u, 3005u, a_AMV_VF_NONE},   /* smime-crl-file */
   {237746033u, 3020u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* smime-encrypt */
   {2767628932u, 3034u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* smime-force-encryption */
   {1005584095u, 3057u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE},   /* smime-no-default-ca */
   {2610149716u, 3077u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* smime-sign */
   {4112782207u, 3088u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* smime-sign-cert */
   {1704393517u, 3104u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* smime-sign-digest */
   {2740251050u, 3122u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* smime-sign-include-certs */
   {3761658326u, 3147u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* smime-sign-message-digest */
   {1782732536u, 3173u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* smtp */
   {1658958037u, 3178u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* smtp-auth */
   {3638650800u, 3188u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* smtp-auth-password */
   {2020555875u, 3207u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* smtp-auth-user */
   {2452298534u, 3222u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* smtp-config */
   {1820965540u, 3234u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_CHAIN},   /* smtp-hostname */
   {1837607842u, 3248u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* smtp-use-starttls */
   {907387109u, 3266u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* SOCKS5_PROXY */
   {900761917u, 3279u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* SOURCE_DATE_EPOCH */
   {3456900515u, 3297u, a_AMV_VF_NONE|a_AMV_VF_POSNUM},   /* socket-connect-timeout */
   {3775764645u, 3320u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_NOTEMPTY|a_AMV_VF_CHAIN},   /* socks-proxy */
   {1607330400u, 3332u, a_AMV_VF_NONE},   /* spam-interface */
   {1763068644u, 3347u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_POSNUM},   /* spam-maxsize */
   {1908563950u, 3360u, a_AMV_VF_NONE},   /* spamc-command */
   {1452123120u, 3374u, a_AMV_VF_NONE},   /* spamc-arguments */
   {4013666858u, 3390u, a_AMV_VF_NONE},   /* spamc-user */
   {1923764058u, 3401u, a_AMV_VF_NONE},   /* spamfilter-ham */
   {3955925583u, 3416u, a_AMV_VF_NONE},   /* spamfilter-noham */
   {3561917382u, 3433u, a_AMV_VF_NONE},   /* spamfilter-nospam */
   {261790554u, 3451u, a_AMV_VF_NONE},   /* spamfilter-rate */
   {914178751u, 3467u, a_AMV_VF_NONE},   /* spamfilter-rate-scanscore */
   {2230056064u, 3493u, a_AMV_VF_NONE},   /* spamfilter-spam */
   {1769124455u, 3509u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-ca-dir */
   {1778108319u, 3520u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-ca-file */
   {3110362859u, 3532u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-ca-flags */
   {623065149u, 3545u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-ca-no-defaults */
   {139775082u, 3564u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-cert */
   {2317777583u, 3573u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-cipher-list */
   {3936220190u, 3589u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* ssl-config-file */
   {315983966u, 3605u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-config-module */
   {1105329479u, 3623u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-config-pairs */
   {800287693u, 3640u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-curves */
   {542424727u, 3651u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* ssl-crl-dir */
   {1605928646u, 3663u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* ssl-crl-file */
   {2392084957u, 3676u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_OBSOLETE},   /* ssl-features */
   {4242392148u, 3689u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-key */
   {842733395u, 3697u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-method */
   {120659094u, 3708u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_OBSOLETE},   /* ssl-no-default-ca */
   {3391235883u, 3726u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-protocol */
   {2493237115u, 3739u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* ssl-rand-egd */
   {1150749481u, 3752u, a_AMV_VF_NONE|a_AMV_VF_OBSOLETE},   /* ssl-rand-file */
   {3001703062u, 3766u, a_AMV_VF_NONE|a_AMV_VF_CHAIN|a_AMV_VF_OBSOLETE},   /* ssl-verify */
   {3060393762u, 3777u, a_AMV_VF_NONE},   /* stealthmua */
   {3170554710u, 3788u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* system-mailrc */
   {1689227859u, 3802u, a_AMV_VF_NONE|a_AMV_VF_ENV},   /* TERM */
   {275160966u, 3807u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_IMPORT|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* TMPDIR */
   {2006033901u, 3814u, a_AMV_VF_NONE},   /* termcap */
   {1881431006u, 3822u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* termcap-ca-mode */
   {3874156389u, 3838u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* termcap-disable */
   {49001407u, 3854u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* tls-ca-dir */
   {2310520195u, 3865u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* tls-ca-file */
   {1223767828u, 3877u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* tls-ca-flags */
   {3113270631u, 3890u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_CHAIN},   /* tls-ca-no-defaults */
   {172056861u, 3909u, a_AMV_VF_NONE},   /* tls-config-file */
   {3002246919u, 3925u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* tls-config-module */
   {789322284u, 3943u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* tls-config-pairs */
   {3248783469u, 3960u, a_AMV_VF_NONE},   /* tls-crl-dir */
   {1888319427u, 3972u, a_AMV_VF_NONE},   /* tls-crl-file */
   {4259586683u, 3985u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* tls-features */
   {1139189225u, 3998u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* tls-fingerprint */
   {2530971234u, 4014u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* tls-fingerprint-digest */
   {2971415438u, 4037u, a_AMV_VF_NONE},   /* tls-rand-file */
   {3259662180u, 4051u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* tls-verify */
   {3045770460u, 4062u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY|a_AMV_VF_NUM},   /* toplines */
   {2347832344u, 4071u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* topsqueeze */
   {3335676089u, 4082u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_DEFVAL|a_AMV_VF_NOTEMPTY},   /* ttycharset */
   {807899482u, 4093u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_VIP},   /* typescript-mode */
   {330400956u, 4109u, a_AMV_VF_NONE|a_AMV_VF_RDONLY|a_AMV_VF_IMPORT|a_AMV_VF_ENV},   /* USER */
   {1567917856u, 4114u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_NODEL|a_AMV_VF_I3VAL|a_AMV_VF_POSNUM},   /* umask */
   {875435785u, 4120u, a_AMV_VF_NONE|a_AMV_VF_NOTEMPTY|a_AMV_VF_CHAIN},   /* user */
   {1942497279u, 4125u, a_AMV_VF_NONE|a_AMV_VF_DEFVAL|a_AMV_VF_ENV|a_AMV_VF_NOTEMPTY},   /* VISUAL */
   {691216848u, 4132u, a_AMV_VF_NONE|a_AMV_VF_I3VAL},   /* v15-compat */
   {3973338304u, 4143u, a_AMV_VF_NONE|a_AMV_VF_VIP|a_AMV_VF_POSNUM},   /* verbose */
   {944087093u, 4151u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* version */
   {1337487108u, 4159u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL},   /* version-date */
   {3081657388u, 4172u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM},   /* version-hexnum */
   {1921844491u, 4187u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM},   /* version-major */
   {1707804737u, 4201u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM},   /* version-minor */
   {3760910668u, 4215u, a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM},   /* version-update */
   {432301395u, 4230u, a_AMV_VF_NONE|a_AMV_VF_BOOL},   /* writebackedited */
   {1643918527u, 4246u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_CHAIN},   /* disconnected */
   {259555527u, 4259u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* imap-auth */
   {3710399665u, 4269u, a_AMV_VF_NONE},   /* imap-cache */
   {3006849165u, 4280u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* imap-delim */
   {1681336106u, 4291u, a_AMV_VF_NONE|a_AMV_VF_CHAIN},   /* imap-keepalive */
   {3435503022u, 4306u, a_AMV_VF_NONE},   /* imap-list-depth */
   {2746817971u, 4322u, a_AMV_VF_NONE|a_AMV_VF_BOOL|a_AMV_VF_CHAIN},   /* imap-use-starttls */
   {1557856483u, 4340u, a_AMV_VF_NONE|a_AMV_VF_ENV},   /* _S_MAILX_TEST */
};

#ifndef a__CREATE_OKEY_MAP_PL
# undef a_X
# ifdef mx_HAVE_PUTENV
#  define a_X(X) X
# else
#  define a_X(X)
# endif

CTAV(4 == FIELD_SIZEOF(struct a_amv_var_chain_map_bsrch, avcmb_prefix));
static struct a_amv_var_chain_map const a_amv_var_chain_map[] = {
   {4246u, ok_b_disconnected},
   {4259u, ok_v_imap_auth},
   {4280u, ok_v_imap_delim},
   {4291u, ok_v_imap_keepalive},
   {4322u, ok_b_imap_use_starttls},
   {1992u, ok_b_netrc_lookup},
   {2279u, ok_v_password},
   {2296u, ok_v_pop3_auth},
   {2336u, ok_b_pop3_no_apop},
   {2349u, ok_b_pop3_use_starttls},
   {2978u, ok_v_smime_cipher},
   {3020u, ok_v_smime_encrypt},
   {3088u, ok_v_smime_sign_cert},
   {3104u, ok_v_smime_sign_digest},
   {3122u, ok_v_smime_sign_include_certs},
   {3147u, ok_v_smime_sign_message_digest},
   {3178u, ok_v_smtp_auth},
   {3222u, ok_v_smtp_config},
   {3234u, ok_v_smtp_hostname},
   {3248u, ok_b_smtp_use_starttls},
   {3320u, ok_v_socks_proxy},
   {3509u, ok_v_ssl_ca_dir},
   {3520u, ok_v_ssl_ca_file},
   {3532u, ok_v_ssl_ca_flags},
   {3545u, ok_b_ssl_ca_no_defaults},
   {3564u, ok_v_ssl_cert},
   {3573u, ok_v_ssl_cipher_list},
   {3605u, ok_v_ssl_config_module},
   {3623u, ok_v_ssl_config_pairs},
   {3640u, ok_v_ssl_curves},
   {3689u, ok_v_ssl_key},
   {3697u, ok_v_ssl_method},
   {3726u, ok_v_ssl_protocol},
   {3766u, ok_v_ssl_verify},
   {3854u, ok_v_tls_ca_dir},
   {3865u, ok_v_tls_ca_file},
   {3877u, ok_v_tls_ca_flags},
   {3890u, ok_b_tls_ca_no_defaults},
   {3925u, ok_v_tls_config_module},
   {3943u, ok_v_tls_config_pairs},
   {3998u, ok_v_tls_fingerprint},
   {4014u, ok_v_tls_fingerprint_digest},
   {4051u, ok_v_tls_verify},
   {4120u, ok_v_user},
};
#define a_AMV_VAR_CHAIN_MAP_CNT 44

static struct a_amv_var_chain_map_bsrch const a_amv_var_chain_map_bsrch[] = {
   {"disc", 0u, ok_b_disconnected},
   {"imap", 1u, ok_b_imap_use_starttls},
   {"netr", 5u, ok_b_netrc_lookup},
   {"pass", 6u, ok_v_password},
   {"pop3", 7u, ok_b_pop3_use_starttls},
   {"smim", 10u, ok_v_smime_sign_message_digest},
   {"smtp", 16u, ok_b_smtp_use_starttls},
   {"sock", 20u, ok_v_socks_proxy},
   {"ssl-", 21u, ok_v_ssl_verify},
   {"tls-", 34u, ok_v_tls_verify},
   {"user", 43u, ok_v_user},
};
#define a_AMV_VAR_CHAIN_MAP_BSRCH_CNT 11

/* Unfortunately init of varsized buffer impossible: define "subclass"es */
static char const a_amv_var_virt_build_cc_val[] = {VAL_BUILD_CC_ARRAY};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[8 +1];
} const a_amv_var_virt_build_cc = {NIL, a_amv_var_virt_build_cc_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "build-cc"};

static char const a_amv_var_virt_build_ld_val[] = {VAL_BUILD_LD_ARRAY};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[8 +1];
} const a_amv_var_virt_build_ld = {NIL, a_amv_var_virt_build_ld_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "build-ld"};

static char const a_amv_var_virt_build_os_val[] = {VAL_BUILD_OS};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[8 +1];
} const a_amv_var_virt_build_os = {NIL, a_amv_var_virt_build_os_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "build-os"};

static char const a_amv_var_virt_build_rest_val[] = {VAL_BUILD_REST_ARRAY};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[10 +1];
} const a_amv_var_virt_build_rest = {NIL, a_amv_var_virt_build_rest_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "build-rest"};

static char const a_amv_var_virt_contact_mail_val[] = {VAL_CONTACT_MAIL};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[12 +1];
} const a_amv_var_virt_contact_mail = {NIL, a_amv_var_virt_contact_mail_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "contact-mail"};

static char const a_amv_var_virt_contact_web_val[] = {VAL_CONTACT_WEB};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[11 +1];
} const a_amv_var_virt_contact_web = {NIL, a_amv_var_virt_contact_web_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "contact-web"};

static char const a_amv_var_virt_features_val[] = {VAL_FEATURES};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[8 +1];
} const a_amv_var_virt_features = {NIL, a_amv_var_virt_features_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "features"};

static char const a_amv_var_virt_ssl_features_val[] = {VAL_TLS_FEATURES};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[12 +1];
} const a_amv_var_virt_ssl_features = {NIL, a_amv_var_virt_ssl_features_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_OBSOLETE, "ssl-features"};

static char const a_amv_var_virt_system_mailrc_val[] = {VAL_SYSCONFDIR "/" VAL_SYSCONFRC};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[13 +1];
} const a_amv_var_virt_system_mailrc = {NIL, a_amv_var_virt_system_mailrc_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "system-mailrc"};

static char const a_amv_var_virt_tls_features_val[] = {VAL_TLS_FEATURES};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[12 +1];
} const a_amv_var_virt_tls_features = {NIL, a_amv_var_virt_tls_features_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "tls-features"};

static char const a_amv_var_virt_version_val[] = {mx_VERSION};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[7 +1];
} const a_amv_var_virt_version = {NIL, a_amv_var_virt_version_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "version"};

static char const a_amv_var_virt_version_date_val[] = {mx_VERSION_DATE};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[12 +1];
} const a_amv_var_virt_version_date = {NIL, a_amv_var_virt_version_date_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL, "version-date"};

static char const a_amv_var_virt_version_hexnum_val[] = {mx_VERSION_HEXNUM};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[14 +1];
} const a_amv_var_virt_version_hexnum = {NIL, a_amv_var_virt_version_hexnum_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM, "version-hexnum"};

static char const a_amv_var_virt_version_major_val[] = {mx_VERSION_MAJOR};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[13 +1];
} const a_amv_var_virt_version_major = {NIL, a_amv_var_virt_version_major_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM, "version-major"};

static char const a_amv_var_virt_version_minor_val[] = {mx_VERSION_MINOR};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[13 +1];
} const a_amv_var_virt_version_minor = {NIL, a_amv_var_virt_version_minor_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM, "version-minor"};

static char const a_amv_var_virt_version_update_val[] = {mx_VERSION_UPDATE};
static struct{
   struct a_amv_var *av_link;
   char const *av_value;
   a_X(char *av_env;)
   u32 av_flags;
   char const av_name[14 +1];
} const a_amv_var_virt_version_update = {NIL, a_amv_var_virt_version_update_val, a_X(0 su_COMMA) a_AMV_VF_NONE|a_AMV_VF_VIRT|a_AMV_VF_RDONLY|a_AMV_VF_NODEL|a_AMV_VF_POSNUM, "version-update"};

static struct a_amv_var_virt const a_amv_var_virts[] = {
   {ok_v_build_cc, {0,}, (void const*)&a_amv_var_virt_build_cc},
   {ok_v_build_ld, {0,}, (void const*)&a_amv_var_virt_build_ld},
   {ok_v_build_os, {0,}, (void const*)&a_amv_var_virt_build_os},
   {ok_v_build_rest, {0,}, (void const*)&a_amv_var_virt_build_rest},
   {ok_v_contact_mail, {0,}, (void const*)&a_amv_var_virt_contact_mail},
   {ok_v_contact_web, {0,}, (void const*)&a_amv_var_virt_contact_web},
   {ok_v_features, {0,}, (void const*)&a_amv_var_virt_features},
   {ok_v_ssl_features, {0,}, (void const*)&a_amv_var_virt_ssl_features},
   {ok_v_system_mailrc, {0,}, (void const*)&a_amv_var_virt_system_mailrc},
   {ok_v_tls_features, {0,}, (void const*)&a_amv_var_virt_tls_features},
   {ok_v_version, {0,}, (void const*)&a_amv_var_virt_version},
   {ok_v_version_date, {0,}, (void const*)&a_amv_var_virt_version_date},
   {ok_v_version_hexnum, {0,}, (void const*)&a_amv_var_virt_version_hexnum},
   {ok_v_version_major, {0,}, (void const*)&a_amv_var_virt_version_major},
   {ok_v_version_minor, {0,}, (void const*)&a_amv_var_virt_version_minor},
   {ok_v_version_update, {0,}, (void const*)&a_amv_var_virt_version_update},
};
#define a_AMV_VAR_VIRTS_CNT 16

static struct a_amv_var_defval const a_amv_var_i3vals[] = {
   {ok_b_asksub, {0,}, NIL},
   {ok_v_datefield, {0,}, "%Y-%m-%d %H:%M"},
   {ok_v_datefield_markout_older, {0,}, "%Y-%m-%d"},
   {ok_b_header, {0,}, NIL},
   {ok_v_ifs_ws, {0,}, " \t\n"},
   {ok_v_log_prefix, {0,}, VAL_UAGENT ": "},
   {ok_b_mbox_fcc_and_pcc, {0,}, NIL},
   {ok_v_prompt, {0,}, "? "},
   {ok_v_prompt2, {0,}, ".. "},
   {ok_b_save, {0,}, NIL},
   {ok_v_sendwait, {0,}, ""},
   {ok_v_umask, {0,}, "0077"},
   {ok_v_v15_compat, {0,}, "y"},
};
#define a_AMV_VAR_I3VALS_CNT 13

static struct a_amv_var_defval const a_amv_var_defvals[] = {
   {ok_v_bind_inter_byte_timeout, {0,}, mx_BIND_INTER_BYTE_TIMEOUT},
   {ok_v_charset_7bit, {0,}, CHARSET_7BIT},
   {ok_v_charset_8bit, {0,}, CHARSET_8BIT},
   {ok_v_content_description_forwarded_message, {0,}, mx_CONTENT_DESC_FORWARDED_MESSAGE},
   {ok_v_content_description_quote_attachment, {0,}, mx_CONTENT_DESC_QUOTE_ATTACHMENT},
   {ok_v_content_description_smime_message, {0,}, mx_CONTENT_DESC_SMIME_MESSAGE},
   {ok_v_content_description_smime_signature, {0,}, mx_CONTENT_DESC_SMIME_SIG},
   {ok_v_DEAD, {0,}, VAL_DEAD},
   {ok_v_EDITOR, {0,}, VAL_EDITOR},
   {ok_v_errors_limit, {0,}, VAL_ERRORS_LIMIT},
   {ok_v_escape, {0,}, n_ESCAPE},
   {ok_v_ifs, {0,}, " \t\n"},
   {ok_v_indentprefix, {0,}, "\t"},
   {ok_v_line_editor_cpl_word_breaks, {0,}, n_LINE_EDITOR_CPL_WORD_BREAKS},
   {ok_v_LISTER, {0,}, VAL_LISTER},
   {ok_v_MAILCAPS, {0,}, VAL_MAILCAPS},
   {ok_v_MAILRC, {0,}, VAL_MAILRC},
   {ok_v_MBOX, {0,}, VAL_MBOX},
   {ok_v_mta, {0,}, VAL_MTA},
   {ok_v_mta_argv0, {0,}, VAL_MTA_ARGV0},
   {ok_v_NETRC, {0,}, VAL_NETRC},
   {ok_v_PAGER, {0,}, VAL_PAGER},
   {ok_v_quote_chars, {0,}, ">|}:"},
   {ok_v_SHELL, {0,}, VAL_SHELL},
   {ok_v_TMPDIR, {0,}, VAL_TMPDIR},
   {ok_v_toplines, {0,}, "5"},
   {ok_v_ttycharset, {0,}, CHARSET_8BIT},
   {ok_v_VISUAL, {0,}, VAL_VISUAL},
};
#define a_AMV_VAR_DEFVALS_CNT 28

#define a_AMV_VAR__SPECIAL_PARAM_MAP_IDX 0u
#define a_AMV_VAR__QM_MAP_IDX 1u
#define a_AMV_VAR__EM_MAP_IDX 2u

# undef a_X
#endif /* !a__CREATE_OKEY_MAP_PL */
#define a_AMV_VAR_REV_ILL 329u
#define a_AMV_VAR_REV_PRIME 619u
#define a_AMV_VAR_REV_LONGEST 6u
#define a_AMV_VAR_REV_WRAPAROUND 0
static u16 const a_amv_var_revmap[a_AMV_VAR_REV_PRIME] = {
  215u, 162u, 329u, 329u, 170u, 329u, 246u, 281u, 305u, 329u,
  2u, 23u, 254u, 329u, 329u, 141u, 329u, 119u, 122u, 329u,
  24u, 329u, 329u, 329u, 329u, 47u, 235u, 302u, 329u, 329u,
  329u, 28u, 214u, 151u, 329u, 121u, 182u, 144u, 236u, 253u,
  329u, 329u, 178u, 206u, 71u, 245u, 289u, 329u, 329u, 329u,
  217u, 329u, 329u, 56u, 64u, 314u, 329u, 329u, 329u, 329u,
  148u, 329u, 53u, 329u, 227u, 329u, 329u, 329u, 329u, 329u,
  329u, 329u, 85u, 6u, 329u, 329u, 329u, 329u, 39u, 79u,
  136u, 112u, 234u, 299u, 329u, 329u, 329u, 329u, 113u, 329u,
  156u, 329u, 329u, 329u, 329u, 329u, 157u, 329u, 42u, 166u,
  329u, 72u, 296u, 329u, 329u, 329u, 12u, 105u, 329u, 329u,
  329u, 259u, 329u, 329u, 329u, 329u, 329u, 329u, 329u, 329u,
  73u, 143u, 329u, 237u, 329u, 92u, 329u, 329u, 329u, 232u,
  276u, 290u, 329u, 103u, 31u, 203u, 303u, 329u, 65u, 54u,
  329u, 20u, 146u, 185u, 309u, 329u, 329u, 98u, 329u, 304u,
  208u, 329u, 68u, 329u, 329u, 329u, 4u, 152u, 241u, 329u,
  329u, 322u, 229u, 155u, 329u, 111u, 329u, 329u, 329u, 329u,
  329u, 199u, 263u, 268u, 329u, 70u, 180u, 266u, 183u, 277u,
  125u, 310u, 329u, 90u, 329u, 329u, 190u, 329u, 139u, 284u,
  83u, 22u, 315u, 329u, 329u, 222u, 140u, 283u, 16u, 300u,
  329u, 329u, 329u, 160u, 329u, 161u, 251u, 313u, 329u, 158u,
  82u, 211u, 329u, 329u, 123u, 168u, 188u, 329u, 94u, 329u,
  329u, 329u, 329u, 165u, 306u, 329u, 130u, 293u, 329u, 329u,
  329u, 329u, 329u, 173u, 210u, 329u, 223u, 7u, 329u, 45u,
  137u, 147u, 118u, 197u, 262u, 294u, 80u, 329u, 77u, 329u,
  11u, 184u, 172u, 89u, 329u, 35u, 108u, 135u, 200u, 325u,
  38u, 329u, 329u, 15u, 329u, 329u, 329u, 329u, 194u, 101u,
  329u, 150u, 329u, 329u, 329u, 213u, 209u, 329u, 240u, 5u,
  76u, 242u, 134u, 329u, 329u, 84u, 329u, 226u, 225u, 329u,
  329u, 329u, 256u, 329u, 329u, 329u, 81u, 329u, 329u, 329u,
  329u, 329u, 329u, 329u, 44u, 75u, 329u, 329u, 132u, 250u,
  329u, 192u, 275u, 9u, 288u, 329u, 329u, 329u, 329u, 329u,
  58u, 301u, 329u, 329u, 329u, 91u, 212u, 186u, 329u, 329u,
  329u, 329u, 329u, 329u, 189u, 116u, 133u, 88u, 252u, 164u,
  109u, 74u, 324u, 329u, 329u, 329u, 329u, 297u, 19u, 329u,
  69u, 86u, 154u, 3u, 329u, 295u, 181u, 329u, 329u, 329u,
  329u, 329u, 41u, 115u, 36u, 329u, 25u, 287u, 271u, 329u,
  329u, 145u, 191u, 169u, 29u, 319u, 329u, 329u, 138u, 329u,
  311u, 17u, 285u, 329u, 329u, 329u, 329u, 329u, 323u, 329u,
  52u, 129u, 8u, 124u, 329u, 329u, 329u, 329u, 329u, 329u,
  329u, 59u, 329u, 174u, 179u, 329u, 230u, 55u, 193u, 228u,
  114u, 196u, 204u, 326u, 329u, 329u, 329u, 329u, 329u, 167u,
  329u, 308u, 0u, 329u, 329u, 329u, 177u, 329u, 269u, 329u,
  61u, 329u, 128u, 243u, 279u, 329u, 329u, 329u, 329u, 329u,
  329u, 106u, 280u, 329u, 329u, 329u, 87u, 329u, 329u, 207u,
  221u, 30u, 318u, 329u, 329u, 329u, 99u, 33u, 329u, 329u,
  329u, 320u, 107u, 329u, 46u, 171u, 329u, 329u, 329u, 102u,
  198u, 329u, 329u, 329u, 329u, 329u, 329u, 329u, 329u, 329u,
  329u, 126u, 329u, 329u, 10u, 21u, 48u, 329u, 159u, 60u,
  117u, 264u, 187u, 247u, 307u, 292u, 329u, 32u, 120u, 127u,
  255u, 329u, 329u, 50u, 142u, 43u, 51u, 57u, 298u, 329u,
  329u, 218u, 329u, 224u, 233u, 329u, 329u, 265u, 231u, 18u,
  93u, 149u, 278u, 327u, 329u, 67u, 100u, 317u, 37u, 329u,
  329u, 329u, 329u, 329u, 329u, 329u, 329u, 329u, 163u, 238u,
  329u, 329u, 329u, 329u, 202u, 249u, 272u, 329u, 97u, 267u,
  329u, 329u, 205u, 316u, 261u, 195u, 220u, 329u, 153u, 329u,
  270u, 14u, 78u, 49u, 104u, 34u, 291u, 329u, 329u, 239u,
  27u, 63u, 329u, 329u, 201u, 216u, 110u, 257u, 258u, 329u,
  248u, 176u, 329u, 329u, 329u, 329u, 329u, 329u, 329u, 329u,
  329u, 329u, 66u, 329u, 312u, 329u, 329u, 329u, 260u, 273u,
  1u, 95u, 244u, 282u, 329u, 219u, 13u, 329u, 26u, 329u,
  286u, 321u, 62u, 96u, 328u, 131u, 175u, 274u, 40u
};
